// 'use server'

import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import { SWRConfig } from 'swr'
import { fetcher } from '../utils/fetcher'
import SWRProvider from './components/SWRProvider'
import { TimerProvider } from './Context/TimerContext'

const noto = Noto_Sans({ subsets: ['latin'], weight: ['300', '400', '700'] })

export const metadata: Metadata = {
  title: 'Calendlix',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <SWRProvider>
          <main className="container flex flex-col max-h-screen min-h-screen">
            <Header />
            <TimerProvider>{children}</TimerProvider>
          </main>
        </SWRProvider>
      </body>
    </html>
  )
}
